version: '3.9'
services:
  db:
    image: mongo
    container_name: storage_mongo
    restart: unless-stopped
    env_file:
      - ./mongo/.env
    networks:
      - app-network
    volumes:
      - dbdata:/data/db

  storage:
    depends_on:
      - db
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: storage_api
    restart: unless-stopped
    env_file:
      - ./api/.env
    volumes:
      - ./storage/files:/files
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local